### ISSUE TITLE
Switch cluster and namespace context

### ISSUE THREAD

**Issue by wvdeutekom** [wvdeutekom/kut#1]
I'd like to be able to switch between clusters and namespaces. Suggestions:

```
kut switch [cluster] [namespace]
kut sw [cluster] [namespace]
```

However, I can imagine that for many users switching between clusters is a less used feature. So always providing a cluster name can be cumbersome.

```
kut namespace [namespace]
kut ns [namespace]
```

```
kut cluster [cluster]
kut cl [cluster]
```

@soudy Thoughts?

**Comment by soudy** [comment]
I prefer separating the two commands, where `kut cl` takes an optional second argument `namespace`, which defaults to `default`.

**Comment by soudy** [comment]
Implemented as `kut ctx [cluster] [namespace]`.
