### ISSUE TITLE
Show current namespace

### ISSUE THREAD

**Issue by wvdeutekom** [wvdeutekom/kut#2]
Working with namespaces can become unclear when services, deployments and ingresses are named ambiguously like `api` `web` or `bot`. To keep track of your current namespace it would be nice to be able to immediately see what namespace your context is currently set at.

Suggestion:
Make sure `$PS1` is set to the current context.

**Comment by soudy** [comment]
We should make this a command and leave it up to the shell to implement it into a function which can be added to your `$PS1`. :+1:

**Comment by wvdeutekom** [comment]
Yes, and once the command has been run: display copy-pasta text you can put in your zsh/bash profile.

**Comment by soudy** [comment]
Implemented in #4
